// Generated by python3 scripts/baku-eyes.py; coordinates/radii are normalized.
import type { BakuPose } from '@/components/Baku';

export const BAKU_SPRITE_PIXELS = 144;
export type BakuEye = { cx: number; cy: number; pupilR: number; whiteR: number; whiteColor: readonly [number, number, number] };

export const bakuEyes: Record<BakuPose, readonly BakuEye[]> = {
  "idle": [
    {
      "cx": 0.37881944,
      "cy": 0.646875,
      "pupilR": 0.02825172,
      "whiteR": 0.0404045,
      "whiteColor": [
        0.83529412,
        0.81960784,
        0.81960784
      ]
    }
  ],
  "chewing": [
    {
      "cx": 0.4390015,
      "cy": 0.64583333,
      "pupilR": 0.02730438,
      "whiteR": 0.04466549,
      "whiteColor": [
        0.83529412,
        0.80784314,
        0.81176471
      ]
    },
    {
      "cx": 0.25868056,
      "cy": 0.62326389,
      "pupilR": 0.01130819,
      "whiteR": 0.02693319,
      "whiteColor": [
        0.83921569,
        0.81176471,
        0.82352941
      ]
    }
  ],
  "success": [],
  "empty": [],
  "errorBrief": [],
  "errorPhoto": [],
  "notFound": [
    {
      "cx": 0.48395594,
      "cy": 0.60201149,
      "pupilR": 0.02457121,
      "whiteR": 0.0384601,
      "whiteColor": [
        0.84901961,
        0.82745098,
        0.82941176
      ]
    },
    {
      "cx": 0.31558642,
      "cy": 0.58024691,
      "pupilR": 0.01844987,
      "whiteR": 0.04101931,
      "whiteColor": [
        0.87058824,
        0.83137255,
        0.81960784
      ]
    }
  ]
};
