// Metro groups @1x/@2x/@3x behind each base-path require. Skia’s native
// loader uses Image.resolveAssetSource, which selects via PixelRatio.get().
export const bakuTintAssets = {
  idle: [
    require('../../assets/baku-v6/baku-idle.png'),
    require('../../assets/baku-v6/baku-idle-shade.png'),
    require('../../assets/baku-v6/baku-idle-band1.png'),
    require('../../assets/baku-v6/baku-idle-band2.png'),
    require('../../assets/baku-v6/baku-idle-band3.png'),
    require('../../assets/baku-v6/baku-idle-band4.png'),
    require('../../assets/baku-v6/baku-idle-band5.png'),
    require('../../assets/baku-v6/baku-idle-band6.png'),
  ],
  chewing: [
    require('../../assets/baku-v6/baku-chewing.png'),
    require('../../assets/baku-v6/baku-chewing-shade.png'),
    require('../../assets/baku-v6/baku-chewing-band1.png'),
    require('../../assets/baku-v6/baku-chewing-band2.png'),
    require('../../assets/baku-v6/baku-chewing-band3.png'),
    require('../../assets/baku-v6/baku-chewing-band4.png'),
    require('../../assets/baku-v6/baku-chewing-band5.png'),
    require('../../assets/baku-v6/baku-chewing-band6.png'),
  ],
  success: [
    require('../../assets/baku-v6/baku-success.png'),
    require('../../assets/baku-v6/baku-success-shade.png'),
    require('../../assets/baku-v6/baku-success-band1.png'),
    require('../../assets/baku-v6/baku-success-band2.png'),
    require('../../assets/baku-v6/baku-success-band3.png'),
    require('../../assets/baku-v6/baku-success-band4.png'),
    require('../../assets/baku-v6/baku-success-band5.png'),
    require('../../assets/baku-v6/baku-success-band6.png'),
  ],
  errorBrief: [
    require('../../assets/baku-v6/baku-error-brief.png'),
    require('../../assets/baku-v6/baku-error-brief-shade.png'),
    require('../../assets/baku-v6/baku-error-brief-band1.png'),
    require('../../assets/baku-v6/baku-error-brief-band2.png'),
    require('../../assets/baku-v6/baku-error-brief-band3.png'),
    require('../../assets/baku-v6/baku-error-brief-band4.png'),
    require('../../assets/baku-v6/baku-error-brief-band5.png'),
    require('../../assets/baku-v6/baku-error-brief-band6.png'),
  ],
  errorPhoto: [
    require('../../assets/baku-v6/baku-error-photo.png'),
    require('../../assets/baku-v6/baku-error-photo-shade.png'),
    require('../../assets/baku-v6/baku-error-photo-band1.png'),
    require('../../assets/baku-v6/baku-error-photo-band2.png'),
    require('../../assets/baku-v6/baku-error-photo-band3.png'),
    require('../../assets/baku-v6/baku-error-photo-band4.png'),
    require('../../assets/baku-v6/baku-error-photo-band5.png'),
    require('../../assets/baku-v6/baku-error-photo-band6.png'),
  ],
  empty: [
    require('../../assets/baku-v6/baku-empty.png'),
    require('../../assets/baku-v6/baku-empty-shade.png'),
    require('../../assets/baku-v6/baku-empty-band1.png'),
    require('../../assets/baku-v6/baku-empty-band2.png'),
    require('../../assets/baku-v6/baku-empty-band3.png'),
    require('../../assets/baku-v6/baku-empty-band4.png'),
    require('../../assets/baku-v6/baku-empty-band5.png'),
    require('../../assets/baku-v6/baku-empty-band6.png'),
  ],
  notFound: [
    require('../../assets/baku-v6/baku-404.png'),
    require('../../assets/baku-v6/baku-404-shade.png'),
    require('../../assets/baku-v6/baku-404-band1.png'),
    require('../../assets/baku-v6/baku-404-band2.png'),
    require('../../assets/baku-v6/baku-404-band3.png'),
    require('../../assets/baku-v6/baku-404-band4.png'),
    require('../../assets/baku-v6/baku-404-band5.png'),
    require('../../assets/baku-v6/baku-404-band6.png'),
  ],
} as const;
