import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const { Skia, AlphaType, ColorType } =
  jest.requireMock<typeof import('@shopify/react-native-skia')>('@shopify/react-native-skia');
const POSES = ['idle', 'chewing', 'success', 'error-brief', 'error-photo', 'empty', '404'];

function pixels(path: string) {
  const image = Skia.Image.MakeImageFromEncoded(Skia.Data.fromBytes(readFileSync(path)))!;
  const width = image.width(), height = image.height();
  const bytes = image.readPixels(0, 0, { width, height, colorType: ColorType.RGBA_8888, alphaType: AlphaType.Unpremul })!;
  image.dispose();
  return { width, height, bytes };
}

// R = original designer alpha; G = silhouette alpha with near-opaque interior
// plateaus and black contact shadow excluded. Generated by baku-clean-edges.py.
// This fixture allows tests to run without the external designer checkout.
const mattes = pixels(resolve(__dirname, '../../tests/fixtures/baku-edge-mattes.png'));

function closest(x: number, y: number, candidates: Uint8Array, size: number) {
  let best = -1, distance = Infinity;
  // Search concentric square perimeters. Once r² exceeds the best distance,
  // no unseen pixel can be closer; row-major index breaks ties like the script.
  for (let radius = 0; radius < size; radius++) {
    for (let dy = -radius; dy <= radius; dy++) for (let dx = -radius; dx <= radius; dx++) {
      if (Math.abs(dx) !== radius && Math.abs(dy) !== radius) continue;
      const nx = x + dx, ny = y + dy;
      if (nx < 0 || nx >= size || ny < 0 || ny >= size) continue;
      const index = ny * size + nx;
      if (!candidates[index]) continue;
      const next = dx * dx + dy * dy;
      if (next < distance || (next === distance && index < best)) { best = index; distance = next; }
    }
    if (distance <= radius * radius) return best;
  }
  if (best < 0) throw new Error('Missing interior/background in source matte');
  return best;
}

test.each(POSES.flatMap((pose, poseIndex) => [1, 2, 3].map((density) => ({ pose, poseIndex, density }))))(
  '$pose (density $density) base, color and shade have no dark matte ring', ({ pose, poseIndex, density }) => {
    const size = 48 * density;
    for (const kind of ['', '-color', '-shade']) {
      const alpha: number[] = [], silhouette: number[] = [];
      for (let y = 0; y < size; y++) for (let x = 0; x < size; x++) {
        const at = (((poseIndex * 3 + density - 1) * 144 + y) * mattes.width + (kind === '-color' ? 144 : 0) + x) * 4;
        alpha.push(mattes.bytes[at]); silhouette.push(mattes.bytes[at + 1]);
      }
      const partial = (at: number) => silhouette[at] > 0 && silhouette[at] < 255;
      const targets: number[] = [], inside = new Uint8Array(size * size), outside = new Uint8Array(size * size);
      for (let y = 0; y < size; y++) for (let x = 0; x < size; x++) {
        const at = y * size + x;
        let nearPartial = false;
        for (let dy = -1; dy <= 1; dy++) for (let dx = -1; dx <= 1; dx++) {
          const nx = x + dx, ny = y + dy;
          if (nx >= 0 && nx < size && ny >= 0 && ny < size && partial(ny * size + nx)) nearPartial = true;
        }
        if (partial(at) || (silhouette[at] === 255 && nearPartial)) targets.push(at);
        if (silhouette[at] === 255 && !nearPartial) inside[at] = 1;
        if (alpha[at] === 0) outside[at] = 1;
      }
      expect(targets.length).toBeGreaterThan(0);
      const suffix = density === 1 ? '' : `@${density}x`;
      const image = pixels(resolve(__dirname, `../../assets/baku-v6/baku-${pose}${kind}${suffix}.png`));
      expect([image.width, image.height]).toEqual([size, size]);
      let maximumDeficit = 0, maximumError = 0;
      for (const at of targets) {
        const x = at % size, y = Math.floor(at / size);
        const interior = closest(x, y, inside, size), background = closest(x, y, outside, size);
        const coverage = alpha[at] / 255;
        for (let channel = 0; channel < 3; channel++) {
          // Shades have a black background, so compare after alpha compositing
          // rather than incorrectly requiring partial shades to equal opaque felt.
          const expected = image.bytes[interior * 4 + channel] * coverage
            + image.bytes[background * 4 + channel] * (1 - coverage);
          const actual = image.bytes[at * 4 + channel];
          maximumDeficit = Math.max(maximumDeficit, expected - actual);
          maximumError = Math.max(maximumError, Math.abs(expected - actual));
        }
        expect(image.bytes[at * 4 + 3]).toBe(255);
      }
      // Allow 2/255 for PNG quantization and the CanvasKit grayscale decoder.
      expect(maximumDeficit).toBeLessThanOrEqual(2);
      expect(maximumError).toBeLessThanOrEqual(2);
    }
  },
);
