"""Regenerate normalized stripe extents from the v6 @3x grayscale masks.

Run from any directory: python3 apps/mobile/scripts/baku-stripe-bounds.py
Bottom is exclusive so even a one-row mask has a nonzero extent.
"""
from pathlib import Path

import numpy as np
from PIL import Image

MOBILE = Path(__file__).resolve().parents[1]
POSES = {
    'idle': 'idle',
    'chewing': 'chewing',
    'success': 'success',
    'errorBrief': 'error-brief',
    'errorPhoto': 'error-photo',
    'empty': 'empty',
    'notFound': '404',
}

lines = [
    '// Generated by scripts/baku-stripe-bounds.py; do not edit by hand.',
    "import type { BakuPose } from '@/components/Baku';",
    '',
    'export type StripeBounds = readonly [top: number, bottom: number] | null;',
    'type PoseStripeBounds = readonly [StripeBounds, StripeBounds, StripeBounds, StripeBounds, StripeBounds, StripeBounds];',
    '',
    'export const bakuStripeBounds = {',
]
for pose, asset in POSES.items():
    lines.append(f'  {pose}: [')
    for band in range(1, 7):
        path = MOBILE / f'assets/baku-v6/baku-{asset}-band{band}@3x.png'
        with Image.open(path) as image:
            mask = np.asarray(image.convert('L'))
        rows = np.flatnonzero(np.any(mask > 0, axis=1))
        if rows.size:
            top = rows[0] / mask.shape[0]
            bottom = (rows[-1] + 1) / mask.shape[0]
            lines.append(f'    [{top:.12f}, {bottom:.12f}],')
        else:
            lines.append('    null,')
    lines.append('  ],')
lines.append('} as const satisfies Record<BakuPose, PoseStripeBounds>;')
(MOBILE / 'src/lib/baku-stripe-bounds.ts').write_text('\n'.join(lines) + '\n')
