#!/usr/bin/env python3
"""Regenerate the checked-in eye geometry from the fixed v6 @3x sprites.

A dark, round connected component must have a mostly bright surrounding ring
and a bounded, neutral white disc. The far eye is examined at a looser threshold;
its white blends into felt, so it is rejected if no bounded disc can be measured.
Closed-eye poses are explicitly excluded: their small arcs can resemble blobs.
"""
from pathlib import Path
import json
import math
import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
POSES = {"idle": "idle", "chewing": "chewing", "success": "success",
         "empty": "empty", "errorBrief": "error-brief",
         "errorPhoto": "error-photo", "notFound": "404"}
CLOSED = {"success", "errorBrief", "errorPhoto"}


def components(mask):
    seen = np.zeros(mask.shape, dtype=bool)
    h, w = mask.shape
    for y, x in zip(*np.where(mask)):
        if seen[y, x]:
            continue
        stack, points = [(y, x)], []
        seen[y, x] = True
        while stack:
            yy, xx = stack.pop()
            points.append((yy, xx))
            for dy in (-1, 0, 1):
                for dx in (-1, 0, 1):
                    ny, nx = yy + dy, xx + dx
                    if 0 <= ny < h and 0 <= nx < w and mask[ny, nx] and not seen[ny, nx]:
                        seen[ny, nx] = True
                        stack.append((ny, nx))
        yield np.array(points)


def detect(path):
    rgba = np.array(Image.open(path).convert("RGBA"))
    rgb = rgba[:, :, :3].astype(float)
    h, w = rgba.shape[:2]
    assert h == w == 144, "Geometry assumes the fixed 144px v6 sprites"
    yy, xx = np.indices((h, w))
    opaque = rgba[:, :, 3] > 200
    bright = (rgb.mean(2) > 170) & opaque
    neutral_white = bright & (np.ptp(rgb, axis=2) < 16)
    found = []
    # The second pass investigates the small far eye without admitting shadows.
    for threshold, minimum in ((70, 4), (90, 2)):
        for points in components((rgb.mean(2) < threshold) & opaque):
            if len(points) < minimum:
                continue
            cy, cx = points.mean(0)
            if any(math.hypot(cx - e["cx"] * w, cy - e["cy"] * h) < 6 for e in found):
                continue
            dimensions = np.ptp(points, axis=0) + 1
            if dimensions.min() / dimensions.max() < 0.6:
                continue
            if len(points) / np.prod(dimensions) < 0.6:
                continue
            core_r = math.sqrt(len(points) / math.pi)
            pupil_r = max(core_r + 0.5, float(np.hypot(points[:, 1] - cx, points[:, 0] - cy).max()) + 0.15)
            distance = np.hypot(xx - cx, yy - cy)
            ring = (distance > core_r + 0.75) & (distance < core_r + 3)
            if bright[ring].mean() < 0.55:
                continue
            # Find the falloff of the neutral white ring, rather than continuing
            # through the warm body or paper. Require a measurable outer edge.
            white_r = None
            for radius in np.arange(pupil_r + 0.75, pupil_r + 6, 0.25):
                annulus = (distance >= radius) & (distance < radius + 1)
                if neutral_white[annulus].mean() < 0.4:
                    white_r = float(radius)
                    break
            if white_r is None or white_r - pupil_r < 0.9:
                continue
            color_ring = ring & neutral_white
            color = np.median(rgb[color_ring], axis=0) / 255
            found.append({"cx": round(float(cx / w), 8), "cy": round(float(cy / h), 8),
                          "pupilR": round(pupil_r / w, 8), "whiteR": round(white_r / w, 8),
                          "whiteColor": [round(float(c), 8) for c in color]})
    return sorted(found, key=lambda e: e["pupilR"], reverse=True)[:2]


def main():
    table = {pose: [] if pose in CLOSED else detect(ROOT / f"assets/baku-v6/baku-{asset}@3x.png")
             for pose, asset in POSES.items()}
    source = "// Generated by python3 scripts/baku-eyes.py; coordinates/radii are normalized.\n"
    source += "import type { BakuPose } from '@/components/Baku';\n\n"
    source += "export const BAKU_SPRITE_PIXELS = 144;\n"
    source += "export type BakuEye = { cx: number; cy: number; pupilR: number; whiteR: number; whiteColor: readonly [number, number, number] };\n\n"
    source += "export const bakuEyes: Record<BakuPose, readonly BakuEye[]> = "
    source += json.dumps(table, indent=2) + ";\n"
    (ROOT / "src/lib/baku-eyes.ts").write_text(source)
    print("pose       cx       cy      pupilR  whiteR  white RGB (@3x pixels)")
    for pose, eyes in table.items():
        if not eyes:
            print(f"{pose:10} —")
        for eye in eyes:
            values = [eye[key] * 144 for key in ("cx", "cy", "pupilR", "whiteR")]
            print(f"{pose:10} " + " ".join(f"{v:8.2f}" for v in values)
                  + "  " + str([round(c * 255) for c in eye["whiteColor"]]))


if __name__ == "__main__":
    main()
