#!/usr/bin/env python3
"""Bundle the original v2 SVG paths for Skia, preserving inherited ink passes."""
import argparse
import json
from pathlib import Path
import xml.etree.ElementTree as ET

parser = argparse.ArgumentParser()
parser.add_argument('--source', type=Path, default=Path('/workspace/inzpo/spec-v2/icons'))
args = parser.parse_args()
icons = {}
for source in sorted(args.source.glob('*.svg')):
    paths = []
    def visit(node, inherited):
        attrs = {**inherited, **node.attrib}
        attrs['opacity'] = float(inherited.get('opacity', 1)) * float(node.attrib.get('opacity', 1))
        if node.tag.rsplit('}', 1)[-1] == 'path':
            paths.append({'d': attrs['d'], 'fill': attrs.get('fill', '#000000'), 'stroke': attrs.get('stroke', 'none'),
                          'strokeWidth': float(attrs.get('stroke-width', 1)), 'opacity': attrs['opacity']})
        for child in node:
            visit(child, attrs)
    visit(ET.parse(source).getroot(), {})
    icons[source.stem] = paths
output = Path(__file__).resolve().parents[1] / 'src' / 'theme' / 'ink-icons.ts'
output.write_text('// Generated by scripts/ink-icons.py from the original Round 5 SVGs.\nexport const inkIcons = '
                  + json.dumps(icons, indent=2) + ' as const;\n')
